name: C/C++ CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get upgrade
        sudo apt-get install cmake llvm-dev clang libboost-dev
    - uses: actions/checkout@v4
    - name: CMake
      run: cmake CMakeLists.txt
